version = 1

# Exclude third-party and generated files from analysis
exclude_patterns = [
  "public/silktide-consent-manager.js",
  "public/silktide-consent-manager.css",
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/coverage/**",
  "**/*.min.js",
  "**/*.min.css",
  "**/vendor/**",
  "docs/_site/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]
  style_guide = "standard"
  skip_doc_coverage = ["function-expression", "arrow-function-expression", "class-expression", "method-definition"]

  # Disable specific rules
  [[analyzers.meta.rules]]
  # Disable JSX maximum depth validation (for forms and complex components)
  path = "**/*Form*.tsx"
  "JS-0415" = { active = false }
  
  [[analyzers.meta.rules]]
  # Also disable for any file that might have forms
  path = "**/*.tsx"
  "JS-0415" = { active = false }

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true