[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund --legacy-peer-deps"

# Production context
[context.production]
  command = "npm ci --legacy-peer-deps && npm run build"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Headers to enable security features
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://etqbojasfmpieigeefdj.supabase.co https://*.sentry.io https://translate.google.com https://translate.googleapis.com; style-src 'self' 'unsafe-inline' https://translate.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://etqbojasfmpieigeefdj.supabase.co https://*.sentry.io wss://*.supabase.co https://api.giveprotocol.io https://*.ingest.sentry.io https://translate.googleapis.com; frame-src 'self' https://translate.google.com;"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Security headers for SVG files
[[headers]]
  for = "/*.svg"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Type = "image/svg+xml"

# Security headers for images
[[headers]]
  for = "/*.png"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.gif"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.webp"
  [headers.values]
    X-Content-Type-Options = "nosniff"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200