# Production-specific Jekyll configuration
# This file overrides settings in _config.yml when building for production

# GitHub Pages configuration
baseurl: "/Duration" # If deploying to github.io/Duration
url: "https://givprotocol.github.io" # Update with your GitHub Pages URL

# Or if using custom domain:
# baseurl: ""
# url: "https://docs.giveprotocol.org"

# Production optimizations
sass:
  style: compressed

# Analytics (add your tracking ID)
google_analytics: "" # Add your Google Analytics ID if needed