# Production-specific Jekyll configuration
# This file overrides settings in _config.yml when building for production

# Custom domain configuration
baseurl: ""
url: "https://docs.giveprotocol.io"

# Production optimizations
sass:
  style: compressed

# Analytics (add your tracking ID)
google_analytics: "" # Add your Google Analytics ID if needed