name: Slither Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install ts-node for TypeScript support
        run: npm install --no-save ts-node @types/node

      - name: Compile contracts
        run: |
          export NODE_OPTIONS="--loader ts-node/esm --no-warnings"
          npx hardhat compile

      - name: Run Slither
        uses: crytic/slither-action@v0.4.1
        with:
          target: '.'
          slither-args: '--compile-force-framework hardhat --filter-paths "node_modules|test|scripts" contracts/'
          sarif: results.sarif
          fail-on: none
          slither-version: 0.10.0

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
        if: always()