name: Solhint Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  solhint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Solhint locally
        run: npm install --save-dev solhint@latest

      - name: List contract files
        run: find contracts -name "*.sol" -type f

      - name: Test individual contract files
        run: |
          echo "Testing individual contract files for syntax errors..."
          for file in contracts/*.sol; do
            echo "Checking $file..."
            npx solhint "$file" -f table || echo "Error in $file"
          done
        continue-on-error: true

      - name: Run Solhint with full output
        run: npx solhint 'contracts/**/*.sol' -f table --max-warnings 100
        continue-on-error: true

      - name: Run Solhint with JSON output
        run: |
          if npx solhint 'contracts/**/*.sol' -f json > solhint-report.json 2>&1; then
            echo "Solhint completed successfully"
          else
            echo "Solhint failed, creating empty report"
            echo '{"reports": []}' > solhint-report.json
          fi
        if: always()

      - name: Upload Solhint report
        uses: actions/upload-artifact@v4
        with:
          name: solhint-report
          path: solhint-report.json
        if: always()